# Generated by Django 4.1.13 on 2024-12-26 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import questions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row1', models.IntegerField(default=0)),
                ('row2', models.IntegerField(default=0)),
                ('row3', models.IntegerField(default=0)),
                ('operation', models.CharField(choices=[('add', 'Add'), ('sub', 'Subtraction')], default='add', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.IntegerField(default=0)),
                ('marks_obtained', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=questions.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
