# Generated by Django 4.1.13 on 2024-12-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
