# Generated by Django 4.1.13 on 2024-12-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_test_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='row1',
            new_name='test_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='question',
            name='row2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='row3',
        ),
    ]
