# Generated by Django 4.1.13 on 2024-12-28 05:44

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_rename_row1_question_test_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_id',
            field=models.IntegerField(default=questions.models.get_default_user),
        ),
    ]
