# Generated by Django 4.1.13 on 2024-12-28 05:51

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_data_alter_question_test_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField(default=questions.models.get_default_user)),
                ('data', models.TextField(default='')),
            ],
        ),
    ]
