# Generated by Django 4.1.13 on 2024-12-28 06:00

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_answeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_id',
            field=models.IntegerField(default=questions.models.get_default_user),
        ),
    ]
