# Generated by Django 4.1.13 on 2024-12-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_delete_answeruser_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
