# Generated by Django 5.1.4 on 2025-01-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_test_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='fullname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
